# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastDist <- function(X, method = "euclidean", diag = FALSE, upper = FALSE, p = 2L) {
    .Call(`_dissimilarities_fastDist`, X, method, diag, upper, p)
}

