# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.expandDistCpp <- function(distA, distBA, distB, diag = FALSE, upper = FALSE) {
    .Call(`_dissimilarities_expandDistCpp`, distA, distBA, distB, diag, upper)
}

.subsetDist2DistCpp <- function(dist, idx, diag = FALSE, upper = FALSE) {
    .Call(`_dissimilarities_subsetDist2DistCpp`, dist, idx, diag, upper)
}

.subsetDist2MatCpp <- function(dist, idx1, idx2) {
    .Call(`_dissimilarities_subsetDist2MatCpp`, dist, idx1, idx2)
}

.subsetColsCpp <- function(dist, colIdx) {
    .Call(`_dissimilarities_subsetColsCpp`, dist, colIdx)
}

.Dist2MatCpp <- function(dist) {
    .Call(`_dissimilarities_Dist2MatCpp`, dist)
}

.fastDistCpp <- function(X, method = "euclidean", diag = FALSE, upper = FALSE, p = 2L) {
    .Call(`_dissimilarities_fastDistCpp`, X, method, diag, upper, p)
}

.fastDistABCpp <- function(A, B, method = "euclidean", p = 2L) {
    .Call(`_dissimilarities_fastDistABCpp`, A, B, method, p)
}

.get1dFrom2dCpp <- function(nr, i, j) {
    .Call(`_dissimilarities_get1dFrom2dCpp`, nr, i, j)
}

.get2dFrom1dCpp <- function(idx, n) {
    .Call(`_dissimilarities_get2dFrom1dCpp`, idx, n)
}

