# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastDistCpp <- function(X, method = "euclidean", diag = FALSE, upper = FALSE, p = 2L) {
    .Call(`_dissimilarities_fastDistCpp`, X, method, diag, upper, p)
}

fastDistABCpp <- function(A, B, method = "euclidean") {
    .Call(`_dissimilarities_fastDistABCpp`, A, B, method)
}

